// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: proto/gophkeeper/v1/gophkeeper.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	AuthKey       []byte                 `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	SaltAuth      []byte                 `protobuf:"bytes,3,opt,name=salt_auth,json=saltAuth,proto3" json:"salt_auth,omitempty"`
	SaltData      []byte                 `protobuf:"bytes,4,opt,name=salt_data,json=saltData,proto3" json:"salt_data,omitempty"`
	KdfVersion    uint32                 `protobuf:"varint,5,opt,name=kdf_version,json=kdfVersion,proto3" json:"kdf_version,omitempty"`
	Verifier      []byte                 `protobuf:"bytes,6,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *RegisterRequest) GetSaltAuth() []byte {
	if x != nil {
		return x.SaltAuth
	}
	return nil
}

func (x *RegisterRequest) GetSaltData() []byte {
	if x != nil {
		return x.SaltData
	}
	return nil
}

func (x *RegisterRequest) GetKdfVersion() uint32 {
	if x != nil {
		return x.KdfVersion
	}
	return 0
}

func (x *RegisterRequest) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	AuthKey       []byte                 `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

type GetSaltsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaltsRequest) Reset() {
	*x = GetSaltsRequest{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaltsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaltsRequest) ProtoMessage() {}

func (x *GetSaltsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaltsRequest.ProtoReflect.Descriptor instead.
func (*GetSaltsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetSaltsRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetSaltsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaltAuth      []byte                 `protobuf:"bytes,1,opt,name=salt_auth,json=saltAuth,proto3" json:"salt_auth,omitempty"`
	KdfVersion    uint32                 `protobuf:"varint,2,opt,name=kdf_version,json=kdfVersion,proto3" json:"kdf_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaltsResponse) Reset() {
	*x = GetSaltsResponse{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaltsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaltsResponse) ProtoMessage() {}

func (x *GetSaltsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaltsResponse.ProtoReflect.Descriptor instead.
func (*GetSaltsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaltsResponse) GetSaltAuth() []byte {
	if x != nil {
		return x.SaltAuth
	}
	return nil
}

func (x *GetSaltsResponse) GetKdfVersion() uint32 {
	if x != nil {
		return x.KdfVersion
	}
	return 0
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SaltAuth      []byte                 `protobuf:"bytes,2,opt,name=salt_auth,json=saltAuth,proto3" json:"salt_auth,omitempty"`
	SaltData      []byte                 `protobuf:"bytes,3,opt,name=salt_data,json=saltData,proto3" json:"salt_data,omitempty"`
	KdfVersion    uint32                 `protobuf:"varint,4,opt,name=kdf_version,json=kdfVersion,proto3" json:"kdf_version,omitempty"`
	Verifier      []byte                 `protobuf:"bytes,5,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetSaltAuth() []byte {
	if x != nil {
		return x.SaltAuth
	}
	return nil
}

func (x *AuthResponse) GetSaltData() []byte {
	if x != nil {
		return x.SaltData
	}
	return nil
}

func (x *AuthResponse) GetKdfVersion() uint32 {
	if x != nil {
		return x.KdfVersion
	}
	return 0
}

func (x *AuthResponse) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	BaseRevision  int64                  `protobuf:"varint,4,opt,name=base_revision,json=baseRevision,proto3" json:"base_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *PushRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PushRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushRequest) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *PushRequest) GetBaseRevision() int64 {
	if x != nil {
		return x.BaseRevision
	}
	return 0
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *PushResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         int64                  `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *PullRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type SecretChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Deleted         bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Revision        int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecretChange) Reset() {
	*x = SecretChange{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretChange) ProtoMessage() {}

func (x *SecretChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretChange.ProtoReflect.Descriptor instead.
func (*SecretChange) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *SecretChange) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretChange) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SecretChange) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SecretChange) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SecretChange) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

// UploadChunk несёт идентификаторы только в первом сообщении потока,
// в остальных заполнено лишь поле data.
type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseRevision  int64                  `protobuf:"varint,2,opt,name=base_revision,json=baseRevision,proto3" json:"base_revision,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *UploadChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadChunk) GetBaseRevision() int64 {
	if x != nil {
		return x.BaseRevision
	}
	return 0
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadChunk) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// Conflict уходит в деталях ошибки FAILED_PRECONDITION: клиент показывает
// пользователю обе версии записи и просит выбрать, какую оставить.
type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       *SecretChange          `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *Conflict) GetCurrent() *SecretChange {
	if x != nil {
		return x.Current
	}
	return nil
}

var File_proto_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_proto_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"$proto/gophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\"\xb9\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\bauth_key\x18\x02 \x01(\fR\aauthKey\x12\x1b\n" +
	"\tsalt_auth\x18\x03 \x01(\fR\bsaltAuth\x12\x1b\n" +
	"\tsalt_data\x18\x04 \x01(\fR\bsaltData\x12\x1f\n" +
	"\vkdf_version\x18\x05 \x01(\rR\n" +
	"kdfVersion\x12\x1a\n" +
	"\bverifier\x18\x06 \x01(\fR\bverifier\"?\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\bauth_key\x18\x02 \x01(\fR\aauthKey\"'\n" +
	"\x0fGetSaltsRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"P\n" +
	"\x10GetSaltsResponse\x12\x1b\n" +
	"\tsalt_auth\x18\x01 \x01(\fR\bsaltAuth\x12\x1f\n" +
	"\vkdf_version\x18\x02 \x01(\rR\n" +
	"kdfVersion\"\x9b\x01\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tsalt_auth\x18\x02 \x01(\fR\bsaltAuth\x12\x1b\n" +
	"\tsalt_data\x18\x03 \x01(\fR\bsaltData\x12\x1f\n" +
	"\vkdf_version\x18\x04 \x01(\rR\n" +
	"kdfVersion\x12\x1a\n" +
	"\bverifier\x18\x05 \x01(\fR\bverifier\"v\n" +
	"\vPushRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12#\n" +
	"\rbase_revision\x18\x04 \x01(\x03R\fbaseRevision\"*\n" +
	"\fPushResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"#\n" +
	"\vPullRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x03R\x05since\"\x9b\x01\n" +
	"\fSecretChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12+\n" +
	"\x12updated_at_unix_ms\x18\x05 \x01(\x03R\x0fupdatedAtUnixMs\"V\n" +
	"\vUploadChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rbase_revision\x18\x02 \x01(\x03R\fbaseRevision\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"!\n" +
	"\x0fDownloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\"A\n" +
	"\bConflict\x125\n" +
	"\acurrent\x18\x01 \x01(\v2\x1b.gophkeeper.v1.SecretChangeR\acurrent2\xe6\x01\n" +
	"\vAuthService\x12G\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12K\n" +
	"\bGetSalts\x12\x1e.gophkeeper.v1.GetSaltsRequest\x1a\x1f.gophkeeper.v1.GetSaltsResponse\x12A\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1b.gophkeeper.v1.AuthResponse2\xa3\x02\n" +
	"\fVaultService\x12?\n" +
	"\x04Push\x12\x1a.gophkeeper.v1.PushRequest\x1a\x1b.gophkeeper.v1.PushResponse\x12A\n" +
	"\x04Pull\x12\x1a.gophkeeper.v1.PullRequest\x1a\x1b.gophkeeper.v1.SecretChange0\x01\x12C\n" +
	"\x06Upload\x12\x1a.gophkeeper.v1.UploadChunk\x1a\x1b.gophkeeper.v1.PushResponse(\x01\x12J\n" +
	"\bDownload\x12\x1e.gophkeeper.v1.DownloadRequest\x1a\x1c.gophkeeper.v1.DownloadChunk0\x01BBZ@github.com/superserj/gophkeeper/proto/gophkeeper/v1;gophkeeperv1b\x06proto3"

var (
	file_proto_gophkeeper_v1_gophkeeper_proto_rawDescOnce sync.Once
	file_proto_gophkeeper_v1_gophkeeper_proto_rawDescData []byte
)

func file_proto_gophkeeper_v1_gophkeeper_proto_rawDescGZIP() []byte {
	file_proto_gophkeeper_v1_gophkeeper_proto_rawDescOnce.Do(func() {
		file_proto_gophkeeper_v1_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_v1_gophkeeper_proto_rawDesc)))
	})
	return file_proto_gophkeeper_v1_gophkeeper_proto_rawDescData
}

var file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: gophkeeper.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: gophkeeper.v1.LoginRequest
	(*GetSaltsRequest)(nil),  // 2: gophkeeper.v1.GetSaltsRequest
	(*GetSaltsResponse)(nil), // 3: gophkeeper.v1.GetSaltsResponse
	(*AuthResponse)(nil),     // 4: gophkeeper.v1.AuthResponse
	(*PushRequest)(nil),      // 5: gophkeeper.v1.PushRequest
	(*PushResponse)(nil),     // 6: gophkeeper.v1.PushResponse
	(*PullRequest)(nil),      // 7: gophkeeper.v1.PullRequest
	(*SecretChange)(nil),     // 8: gophkeeper.v1.SecretChange
	(*UploadChunk)(nil),      // 9: gophkeeper.v1.UploadChunk
	(*DownloadRequest)(nil),  // 10: gophkeeper.v1.DownloadRequest
	(*DownloadChunk)(nil),    // 11: gophkeeper.v1.DownloadChunk
	(*Conflict)(nil),         // 12: gophkeeper.v1.Conflict
}
var file_proto_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	8,  // 0: gophkeeper.v1.Conflict.current:type_name -> gophkeeper.v1.SecretChange
	0,  // 1: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	2,  // 2: gophkeeper.v1.AuthService.GetSalts:input_type -> gophkeeper.v1.GetSaltsRequest
	1,  // 3: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.LoginRequest
	5,  // 4: gophkeeper.v1.VaultService.Push:input_type -> gophkeeper.v1.PushRequest
	7,  // 5: gophkeeper.v1.VaultService.Pull:input_type -> gophkeeper.v1.PullRequest
	9,  // 6: gophkeeper.v1.VaultService.Upload:input_type -> gophkeeper.v1.UploadChunk
	10, // 7: gophkeeper.v1.VaultService.Download:input_type -> gophkeeper.v1.DownloadRequest
	4,  // 8: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.AuthResponse
	3,  // 9: gophkeeper.v1.AuthService.GetSalts:output_type -> gophkeeper.v1.GetSaltsResponse
	4,  // 10: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.AuthResponse
	6,  // 11: gophkeeper.v1.VaultService.Push:output_type -> gophkeeper.v1.PushResponse
	8,  // 12: gophkeeper.v1.VaultService.Pull:output_type -> gophkeeper.v1.SecretChange
	6,  // 13: gophkeeper.v1.VaultService.Upload:output_type -> gophkeeper.v1.PushResponse
	11, // 14: gophkeeper.v1.VaultService.Download:output_type -> gophkeeper.v1.DownloadChunk
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_v1_gophkeeper_proto_init() }
func file_proto_gophkeeper_v1_gophkeeper_proto_init() {
	if File_proto_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_v1_gophkeeper_proto_depIdxs,
		MessageInfos:      file_proto_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_v1_gophkeeper_proto = out.File
	file_proto_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
